language: node_js
node_js:
  - "lts/*"
script:
  - npm run build
  - |
    find ./ \
      -type d \
      -maxdepth 1 \
      -mindepth 1 \
      -name "*" \
      ! -name "dist" \
      ! -name ".git" \
      -exec rm -r {} \;
  - |
    find ./ \
      -type f \
      -maxdepth 1 \
      -mindepth 1 \
      -name "*" \
      ! -name "package.json" \
      ! -name "package-lock.json" \
      -exec rm -r {} \;
deploy:
  provider: heroku
  skip-cleanup: true
  app: webpurple-provider
  api_key:
    secure: $HEROKU_TOKEN
  on:
    branch: master